name = "WildfireData"
uuid = "c50625c8-1a95-45e7-9f30-e55dbed7e5b4"
version = "0.0.2"
authors = ["Josh Day <emailjoshday@gmail.com> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
CSV = "0.10"
DBInterface = "2"
DataFrames = "1"
GeoJSON = "0.8"
HTTP = "1"
JSON3 = "1"
SQLite = "1"
Scratch = "1"
ZipFile = "0.10"
julia = "1.10"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames", "GeoJSON"]
