project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - getting-started.qmd
    - modules/wfigs.qmd
    - modules/irwin.qmd
    - modules/fpa-fod.qmd
    - modules/mtbs.qmd
    - modules/firms.qmd
    - modules/landfire.qmd

website:
  title: "WildfireData.jl"
  description: "Julia package for accessing wildfire and fire-related geospatial data"
  repo-url: https://github.com/joshday/WildfireData.jl
  repo-actions: [issue]
  navbar:
    background: "#8B0000"
    foreground: white
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Getting Started
      - text: Modules
        menu:
          - href: modules/wfigs.qmd
            text: WFIGS
          - href: modules/irwin.qmd
            text: IRWIN
          - href: modules/fpa-fod.qmd
            text: FPA-FOD
          - href: modules/mtbs.qmd
            text: MTBS
          - href: modules/firms.qmd
            text: FIRMS
          - href: modules/landfire.qmd
            text: LANDFIRE
    right:
      - icon: github
        href: https://github.com/joshday/WildfireData.jl

  sidebar:
    style: docked
    search: true
    contents:
      - section: "Overview"
        contents:
          - index.qmd
          - getting-started.qmd
      - section: "Data Modules"
        contents:
          - modules/wfigs.qmd
          - modules/irwin.qmd
          - modules/fpa-fod.qmd
          - modules/mtbs.qmd
          - modules/firms.qmd
          - modules/landfire.qmd

  page-footer:
    center: "WildfireData.jl - Access wildfire data from Julia"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
