[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
LocalCoverage = "5f6e1e16-694c-5876-87ef-16b5274f298e"
WildfireData = "c50625c8-1a95-45e7-9f30-e55dbed7e5b4"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
